### ISSUE TITLE
[Setting] 프로젝트 생성 및 세팅

### ISSUE THREAD

**Issue by Kwonhyunjun** [ONE-TEAM-ONE/OneEat#1]
## 📎 Description
> 프로젝트를 생성하고 기본 설정을 구성합니다.

## ✅ Todo
- [x] **프로젝트 초기 설정**
    - 프로젝트 생성 및 구조 구성
    - 기본 의존성 추가
- [x] **글로벌 응답 및 에러 처리**
    - 공통 응답 구조 정의
    - 예외 핸들링 및 커스텀 에러 메시지 구성
- [x] **Auditing 기능 설정**
    - `BaseEntity` 클래스 구현
- [x] **Swagger 설정**

## 📚 Reference
