### ISSUE TITLE
[REFACTOR] Auth 도메인

### ISSUE THREAD

**Issue by JISU-YANG** [ONE-TEAM-ONE/OneEat#54]
## 📎 Description 
>  Auth 도메인 관련 코드 리팩토링합니다.

## ✅ Todo
- [x] Builder 패턴 제거
- [x] 주석 제거 및 로그 추가
- [x] Valid 필드 추가
- [x] 불필요한 throws 정리
- [x] 컨트롤러에서 데이터 바인딩
- [x] 이메일 중복 검사 추가
