### ISSUE TITLE
[REFACTOR] User 도메인

### ISSUE THREAD

**Issue by JISU-YANG** [ONE-TEAM-ONE/OneEat#59]
## 📎 Description 
> User 도메인 관련 코드를 리팩토링 합니다.

## ✅ Todo
- [x] 컨트롤러에서 데이터 바인딩
- [x] 주석 제거 및 로그 추가
- [x] 이메일 중복 검사 추가
- [x] 닉네임 중복확인 복구
- [x] 이메일 중복검사 추가
- [x] 검증 로직 추가
