### ISSUE TITLE
[REFACTOR] User Address 도메인

### ISSUE THREAD

**Issue by JISU-YANG** [ONE-TEAM-ONE/OneEat#62]
## 📎 Description 
> User Address 도메인 관련 코드를 리팩토링 합니다.

## ✅ Todo
- [x] 컨트롤러에서 데이터 바인딩
- [x] 주석 제거 및 로그 추가
- [x] 검증 로직 분리
- [x] Valid 필드 추가
